services:
  web:
    image: ghcr.io/coremind-llc/sindura_med_service:prod
    container_name: sindura_med_service
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./media:/app/media
      - ./static:/app/static
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      # - db
      - redis

  celery:
    build: .
    container_name: sindura_med_celery
    working_dir: /app
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      - redis
      # - db

  celery-beat:
    build: .
    container_name: sindura_med_celery_beat
    working_dir: /app
    command: celery -A config beat -l info
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      - redis
      # - db

  # db:
  #   image: postgres:18.1-alpine3.23
  #   container_name: db
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #     - ./postgres:/docker-entrypoint-initdb.d
  #   command: >
  #     sh -c "
  #       docker-entrypoint.sh postgres &
  #       until pg_isready -U ${DB_USER}; do sleep 1; done;
  #       psql -U ${DB_USER} -tc \"SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}'\" | grep -q 1 || \
  #       psql -U ${DB_USER} -c \"CREATE DATABASE ${DB_NAME}\";
  #       wait
  #     "

  redis:
    image: redis:7.4.3-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pg_data:

networks:
  default:
    driver: bridge
