# Generated by Django 6.0.1 on 2026-01-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_initial"),
        ("examination", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examination",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
