# Generated by Django 6.0.1 on 2026-01-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0003_examination_date_examination_doctor_examination_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="is_lock",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
