# Generated by Django 6.0.1 on 2026-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0004_examination_is_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="is_lock",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
