# Generated by Django 6.0.1 on 2026-01-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0005_alter_examination_is_lock"),
        ("examination_pack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="examination_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="examination_pack.examinationpack",
            ),
        ),
    ]
