# Generated by Django 6.0.1 on 2026-01-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0006_examination_examination_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
