# Generated by Django 6.0.1 on 2026-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0008_rename_amount_examination_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="room",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
