# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0009_examination_room"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examination",
            options={"ordering": ["-id"]},
        ),
    ]
