# Generated by Django 6.0.1 on 2026-01-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_primary",
        ),
    ]
