# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_doctor_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["-id"]},
        ),
    ]
