# Generated by Django 6.0.1 on 2026-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_type", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationtype",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
