# Generated by Django 6.0.1 on 2026-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_type", "0003_examinationtype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationtype",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
