# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination_type", "0003_examinationtype_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examinationtype",
            options={"ordering": ["-id"]},
        ),
    ]
