# Generated by Django 6.0.1 on 2026-03-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination_type", "0004_alter_examinationtype_options"),
        ("examination_type", "0004_examinationtype_archived"),
    ]

    operations = []
