# Generated by Django 6.0.1 on 2026-02-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="model_name",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("EXAMINATION", "Examination"),
                    ("EXAMINATION_PACK", "Examination pack"),
                    ("EXAMINATION_TYPE", "Examination type"),
                    ("ORDER ", "Order"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
