# Generated by Django 6.0.1 on 2026-02-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity_log",
            "0002_remove_activitylog_model_name_activitylog_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
