# Generated by Django 6.0.1 on 2026-03-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0003_activitylog_body_alter_activitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
