# Generated by Django 6.0.1 on 2026-03-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_log", "0004_activitylog_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("APPROVE", "Approve"),
                    ("CANCEL", "Cancel"),
                    ("DELETE", "Delete"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
