# Generated by Django 6.0.1 on 2026-01-09 01:31

import django.core.validators
import helpers.validator_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        default="ACTIVE",
                        verbose_name=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DELETED", "Deleted"),
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=32,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "register",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(7)],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=8,
                        validators=[
                            helpers.validator_helper.ValidatorHelper.validate_phone,
                            django.core.validators.MinLengthValidator(8),
                        ],
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
