# Generated by Django 6.0.1 on 2026-01-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
