# Generated by Django 6.0.1 on 2026-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_expire_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_refund",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
