# Generated by Django 6.0.1 on 2026-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_is_refund_order_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_manual",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
