# Generated by Django 6.0.1 on 2026-01-29 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_is_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="register",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
