# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_order_register"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
    ]
