# Generated by Django 6.0.1 on 2026-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination_pack", "0002_examinationpack_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examinationpack",
            old_name="amount",
            new_name="deposit_amount",
        ),
        migrations.AddField(
            model_name="examinationpack",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
