# Generated by Django 6.0.1 on 2026-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "examination_pack",
            "0003_rename_amount_examinationpack_deposit_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="examinationpack",
            name="room",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
