# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examination_pack", "0004_examinationpack_room"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examinationpack",
            options={"ordering": ["-id"]},
        ),
    ]
