# Generated by Django 6.0.1 on 2026-02-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_remove_invoice_payment_condition_alter_invoice_stage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-id"]},
        ),
    ]
